# Generated by Django 2.2 on 2019-04-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('parent_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.IntegerField()),
                ('long', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('body', models.TextField()),
                ('keywords', models.TextField()),
                ('publish_time', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('count_view', models.IntegerField()),
                ('code', models.CharField(max_length=15)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('parent_id', models.IntegerField()),
            ],
        ),
    ]
