# Generated by Django 2.2 on 2019-04-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newssite', '0003_auto_20190409_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='postcategory',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postfile',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postfile',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='posttag',
            name='post',
        ),
        migrations.RemoveField(
            model_name='posttag',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ManyToManyField(default=None, to='newssite.Author'),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(default=None, to='newssite.Category'),
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.ManyToManyField(default=None, to='newssite.File'),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(default=None, to='newssite.Tag'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='PostAuthor',
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
        migrations.DeleteModel(
            name='PostFile',
        ),
        migrations.DeleteModel(
            name='PostTag',
        ),
    ]
