# Generated by Django 2.2 on 2019-04-09 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newssite', '0004_auto_20190409_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='newssite.Category'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='parent_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='newssite.Tag'),
        ),
    ]
