# Generated by Django 2.2 on 2019-04-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newssite', '0005_auto_20190409_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
