# Generated by Django 2.2 on 2019-04-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newssite', '0007_auto_20190410_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.IntegerField(choices=[(1, 'pendding'), (2, 'publish'), (3, 'delete'), (4, 'archive')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, 'pendding'), (2, 'publish'), (3, 'delete'), (4, 'archive')]),
        ),
    ]
