# Generated by Django 2.2 on 2019-04-10 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newssite', '0008_auto_20190410_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newssite.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ManyToManyField(to='newssite.Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='newssite.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.ManyToManyField(to='newssite.File'),
        ),
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newssite.Language'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='newssite.Location'),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
